enhance spin files and add spin.yml and start script

diff --git a/detect b/detect
--- a/detect
+++ b/detect
@@ -5,6 +5,11 @@ VERSION="0.0.1"
 echo "spin-ui v${VERSION}"
 
 if ! test -f spin.css || ! test -f spin.js; then
+  if ! command -v node > /dev/null 2>&1 || ! command -v npm > /dev/null 2&1; then
+    echo >&2 "error: Missing node/npm"
+    exit ${ERROR}
+  fi
+
   exit ${NEEDS_COMPILE}
 fi
 
